### ISSUE TITLE
Open sourcing of the ACI integration

### ISSUE THREAD

**Issue by chris-crone** [docker/cloud-integration-beta#1]
The first release of the ACI integration is binary only and does not include the source code. We chose to do this because we need to get the code into a state that those external to Docker can contribute before we can open source it. This includes making sure we have a clear roadmap, documentation for contributing, etc.

Docker will open source the code in the near future.

**Comment by gtardif** [comment]
open-sourced to https://github.com/docker/compose-cli.
See https://www.docker.com/blog/open-source-cloud-compose/
